### ISSUE TITLE
Facade / Tool for gathering post data within the view.

### ISSUE THREAD

**Issue by mennotempelaar** [Bondgenoot/nova-blog-module#12]
### Todo

- [x] Retrieval of news items for inclusion in an overview
- [x] Retrieve latest number of news items
- [x] Retrieving news items from an author
- [x] Add option for pagination
